import { createElement } from '@lwc/engine-dom';
import Money_CX_CreateTransaction from 'c/money_CX_CreateTransaction';

describe('c-money-c-x-create-transaction', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-money-c-x-create-transaction', {
            is: Money_CX_CreateTransaction
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});